#!/bin/bash

GITHOST="$1.suse.de"
BARCLAMP=$2
DEST_FOLDER=$3
UPLOAD=$4
VM_BASE=/opt/dell/chef
GIT_BASE=/home/cloud/barclamp-$BARCLAMP/chef
ALL=('attributes' 'recipes' 'roles')

function usage {
  echo "usage: $0 githost barclamp folder [upload]"
}

if [ $# -lt 3 ] || [ $# -gt 4 ]
then
  usage $0
  exit 0
fi

case $DEST_FOLDER in
  'a'|'attr'|'attributes')
    SERVICE_PATH=$(ssh root@$GITHOST "cd $GIT_BASE; find . -name services.rb | sed 's/^.//'")
    case $BARCLAMP in
      'database')
        for a in $SERVICE_PATH; do
          rsync -v -e ssh root@$GITHOST:$GIT_BASE$a $VM_BASE$a
        done
      ;;
      *)
        rsync -v -e ssh root@$GITHOST:$GIT_BASE$SERVICE_PATH $VM_BASE$SERVICE_PATH
    esac
  ;;
  're'|'recipes')
    RECIPE_PATH=$(ssh root@$GITHOST "cd $GIT_BASE; find . -name deactivate*.rb | sed 's/^.//'")
    for re in $RECIPE_PATH; do
      rsync -v -e ssh root@$GITHOST:$GIT_BASE$re $VM_BASE$re
    done
  ;;
  'ro'|'roles')
    ROLE_PATH=$(ssh root@$GITHOST "cd $GIT_BASE; find . -name $BARCLAMP*_remove.rb | sed 's/^.//'")
    for ro in $ROLE_PATH; do
      rsync -v -e ssh root@$GITHOST:$GIT_BASE$ro $VM_BASE$ro
    done
  ;;
  'all')
    for i in "${ALL[@]}"
    do
      bash $0 $1 $2 $i $4
    done
  ;;
  *)
   usage $0
   exit 0
  ;;
esac

#upload cookbook and role
case $UPLOAD in
  'upload'|'up')
    echo "uploading cookbook $BARCLAMP"
    knife cookbook upload -o $VM_BASE/cookbooks $BARCLAMP
    echo "uploading role $BARCLAMP"
    knife role from file $VM_BASE/roles/$BARCLAMP*_remove.rb
  ;;
  *)
    echo "not uploading cookbooks and roles"
    exit 0
  ;;
esac

exit 0
