#!/bin/bash
#
# sync barclamps from local git checkout to the crobar admin node
#

GITHOST="$1.suse.de"
BARCLAMP=$2
DEST_FOLDER=$3
UPLOAD=$4
VM_BASE=/opt/dell/chef
GIT_BASE=/home/cloud/barclamp-$BARCLAMP/chef
ALL=(attributes recipes roles)
BCS=(database keystone rabbitmq ceph swift glance cinder neutron nova nova_dashboard ceilometer heat)

function usage {
  echo "usage: $0 githost barclamp folder [upload]"
}

# deploy all barclamps to admin node
if [ $2 == "nuke" ]
then
  for bc in "${BCS[@]}"
  do
    for folder in "${ALL[@]}"
    do
      bash $0 $1 $bc $folder "up"
    done
  done
  exit 0
fi

if [ $# -lt 3 ] || [ $# -gt 4 ]
then
  usage $0
  exit 0
fi

# check which folder needs to be synced
# there are: /opt/dell/chef/cookbooks/$BC/attributes
#            /opt/dell/chef/cookbooks/$BC/recipes
#            /opt/dell/chef/roles
case $DEST_FOLDER in
  'a'|'attr'|'attributes')
    DIR=cookbooks/$BARCLAMP/attributes
    SRC=$GIT_BASE/$DIR
    DEST=$VM_BASE/$DIR
    ssh root@$GITHOST ls $GIT_BASE/$DIR/services.rb > /dev/null
    if [ $? -eq 0 ]
    then
      FILES=services.rb
    else
      echo "check for attributes file manually. exit..."
      exit 0
    fi
  ;;
  're'|'recipes')
    DIR=cookbooks/$BARCLAMP/recipes
    SRC=$GIT_BASE/$DIR
    DEST=$VM_BASE/$DIR
    FILES=deactivate*.rb
  ;;
  'ro'|'roles')
    DIR=roles
    SRC=$GIT_BASE/$DIR
    DEST=$VM_BASE/$DIR
    FILES=$BARCLAMP*_remove.rb
  ;;
  'all')
    for i in "${ALL[@]}"
    do
      bash $0 $1 $2 $i $4
    done
  ;;
  *)
   usage $0
   exit 0
  ;;
esac

if [ -z "$SRC" ]
then
  exit 0
fi

#echo "rsync -v --ignore-existing -e ssh root@$GITHOST:$SRC/$FILES $DEST"
rsync -v --ignore-existing -e ssh root@$GITHOST:$SRC/$FILES $DEST

#upload cookbook and role
case $UPLOAD in
  'upload'|'up')
    echo "uploading cookbook $BARCLAMP"
    knife cookbook upload -o $VM_BASE/cookbooks $BARCLAMP
    echo "uploading role $BARCLAMP"
    knife role from file $VM_BASE/roles/$BARCLAMP*_remove.rb
  ;;
  *)
    echo "not uploading cookbooks and roles"
    exit 0
  ;;
esac

exit 0
