#!/bin/bash

nova flavor-create m1.smaller 11 512 10 1

glance image-create --name=jeos-64 --is-public=True --container-format=bare --disk-format=qcow2 --copy-from http://clouddata.cloud.suse.de/images/jeos-64.qcow2
glance image-create --name=ubuntu --is-public=True --container-format=bare --disk-format=qcow2 --copy-from http://uec-images.ubuntu.com/precise/current/precise-server-cloudimg-amd64-disk1.img

sleep 2

nova boot --flavor m1.smaller --image ubuntu ubuntu 
nova boot --flavor m1.smaller --image jeos-64 jeos-64 

nova floating-ip-create
nova add-floating-ip jeos-64 192.168.122.130
nova floating-ip-create
nova add-floating-ip ubuntu 192.168.122.131

nova secgroup-add-rule default icmp -1 -1 0.0.0.0/0
nova secgroup-add-rule default tcp 1 65535 0.0.0.0/0
nova secgroup-add-rule default udp 1 65535 0.0.0.0/0

nova get-vnc-console jeos-64 novnc
nova get-vnc-console ubuntu novnc
